### ISSUE TITLE
Guitar Strings

### ISSUE THREAD

**Issue by Arcayle** [keijiro/Minis#11]
I wanted to know if or how i can find out on what string on the guitar a note has been played. Thanks for the answer :)

**Comment by keijiro** [comment]
Honestly, I have no idea. Minis only accepts MIDI input. Look for a solution that converts guitar playing into MIDI signals.

**Comment by keijiro** [comment]
I'm closing this issue as not relevant to the project. Please feel free to reopen it for further problems.
