### ISSUE TITLE
Crash in MidiDevice.FinishSetup due to null product

### ISSUE THREAD

**Issue by yewnyx** [keijiro/Minis#13]
```
        // MIDI channel number determination
        // Here is a dirty trick: Parse the last two characters in the product
        // name and use it as a channel number.
        var product = description.product;
        channel = int.Parse(product.Substring(product.Length - 2));
```
The product for my MIDI device is null, so this code crashes.

Adding
```
Debug.Log($"{description}|||{description.product}");
```
under the `var product` line results in:
```
<Empty Device Description>|||
```

The device is an Arturia KeyStep: https://www.arturia.com/keystep/overview

**Comment by keijiro** [comment]
Thanks for reporting the issue. Could you tell me which platform you are using? Windows or macOS?

**Comment by keijiro** [comment]
I'm closing this issue now due to inactivity. Please feel free to reopen it for further problems.

**Comment by yewnyx** [comment]
I apologize, I didn't notice the email from GitHub. I was using Windows.
