### ISSUE TITLE
 Control of two midi controllers

### ISSUE THREAD

**Issue by masakazoo1979** [keijiro/Minis#14]
I tried to use Minis to control two midi controllers.
It behaves like a conflict.
The problem: After operating the CC of the midi controller with the Action registered, operating any CC of the other unregistered midi contoroller will cause the CC of the midi controller with the Action registered to stop responding.

The event occurs when the following steps are taken.

1. Attach ScaleByInputValue.cs(Sample Script) to an arbitrary 3D object.
2. Go to Inspector>ScaleByInputValue>Action and attach to any CC(at midi controller No.1).
3. Press the Play button and operate the CC registered in step 2 (at this point, it is confirmed to work properly).
4. Operate any CC of the midi Controller(at midi controller No.2) that is not registered in 2.
5. The 3D Object does not respond when manipulating the CC of the midi Controller(at midi controller No.1) registered in 5.2.

The above event did not occur with midiJack.
Is there something wrong with my settings?

**Comment by keijiro** [comment]
I'd recommend checking the binding path by pressing the "T" button.

<img width="380" alt="Screen Shot 2021-07-14 at 10 53 58 AM" src="https://user-images.githubusercontent.com/343936/125548246-9de66fe0-e114-4095-ae73-3182be4f6236.png">

Please take a look at the reference manual to know how the path works.

https://docs.unity3d.com/Packages/com.unity.inputsystem@1.1/manual/Controls.html#control-paths

If you're using the layout name field (`<MidiDevice>/control001`), it would cause conflicts between multiple devices with the same layout.

It would be better to use the control name field, like `MidiDevice/control001`. It starts getting messages only from the first activated MIDI device. To use the second activated device, change it to `MidiDevice1/control001`.

Or you can use the display name field to specify the device by a human-readable name (e.g. `#(nanoKONTROL2*Channel 0)/control001`). You can check the device name using the Input Debugger.

**Comment by masakazoo1979** [comment]
Thank you!
The problem has been resolved and there is no longer a conflict.
