### ISSUE TITLE
Listen for any note and get its velocity, name, and index?

### ISSUE THREAD

**Issue by the8thbit** [keijiro/Minis#17]
Using the new input system, I can set up listeners for specific notes (e.g. A#3, C4, etc...) and grab their velocities with .get<float>(). But is there a way to listen for any note input and get its velocity, index, and name?

**Comment by keijiro** [comment]
See NoteCallback example.

https://github.com/keijiro/Minis/blob/master/Assets/Script/NoteCallback.cs

**Comment by keijiro** [comment]
I'm closing this issue now. Please feel free to reopen it for further problems.
