### ISSUE TITLE
How to get value of MIDI keyboard key

### ISSUE THREAD

**Issue by ShumWengSang** [keijiro/Minis#18]
Hi Keijiro,

Awesome work as always, I was wondering if it was possible to get the current state of a MIDI key (raw or normalized). I'm trying to replicate in the game-world how 'deeply pressed' the key currently is and both MidiNoteControl and MidiValueControl don't seem to hold this value. 

I understand that some MIDI devices don't have range/axis like a MIDI piano does, so I'm not sure if the information is even available. Regardless, I would love to know for sure.

**Comment by keijiro** [comment]
A short answer is no, the information is not available. The MIDI specifications (standardized in 1983) only provide `0-127` values at each note-on.

**Comment by keijiro** [comment]
I'm closing this issue now. Please feel free to reopen it for further problems.
