### ISSUE TITLE
UWP and x86?

### ISSUE THREAD

**Issue by ShumWengSang** [keijiro/Minis#19]
I'm attempting to develop a Unity app that targets Hololens 1st gen and was wondering if Minis supports that.

Specifically, HoloLens 1 requires applications to be an x86 UWP as well as Midi Over Bluetooth connection.

**Comment by keijiro** [comment]
No, it doesn't support UWP nor x86.

**Comment by keijiro** [comment]
I'm closing this issue now. Please feel free to reopen it for further problems.
