### ISSUE TITLE
Retrigger animation without waiting the end of it

### ISSUE THREAD

**Issue by Drumaddict182** [keijiro/Minis#26]
Hello everyone, I'm using the Minis package to trigger an animation with a midi controller but i have to wait until the end of the animation to trigger it again. How can I retrigger an animation without waiting the end of it ? Thank you.

**Comment by keijiro** [comment]
You may have to set `normalizedTime` to zero: http://answers.unity.com/answers/1679562/view.html

**Comment by keijiro** [comment]
I'm closing this issue now as the original post is not relevant to this specific project (it's a general question about the behavior of the Animator component). Please reopen it for further problem about Minis.
