### ISSUE TITLE
Event handler can't unbind itself

### ISSUE THREAD

**Issue by Tossrock** [keijiro/Minis#28]
Pretty straightforward, in `MidiDevice.cs` the event handler callbacks [are iterated over](https://github.com/keijiro/Minis/blob/7a7e9a4d2c82d84685699108d3f93b9d50e57f12/Packages/jp.keijiro.minis/Runtime/MidiDevice.cs#L96), which means that if an event handler removes itself from the handler list, an exception will be thrown. Simple example:

```c#
public class MidiTester : MonoBehavior {
    public MidiDevice device;

    private void Awake()
    {
        var match = new InputDeviceMatcher().WithInterface("Minis");
        foreach (InputDevice dev in InputSystem.devices){
            if (match.MatchPercentage(device.description) > 0)
                device = dev as MidiDevice;
        }

        device.onWillNoteOn += FirstAction
    }

    private void FirstAction(MidiNoteControl note, float value)
    {
        Debug.Log("First press");
        device.onWillNoteOn -= FirstAction;
        device.onWillNoteOn += SecondAction;
    }

    private void SecondAction(MidiNoteControl note, float value)
    {
       Debug.Log("Later presses");
    }
}

```
<img width="903" alt="CollectionIterationError" src="https://user-images.githubusercontent.com/284311/177100842-8f1798ed-9f68-4495-aecb-b6b2ecd0d479.png">

**Comment by keijiro** [comment]
In my opinion, it's not a good practice to remove a callback function in the function itself.

Do you think it should be supported?

**Comment by Tossrock** [comment]
My use case is that I am dynamically binding MIDI controls to actions at
run time with the same "listen" approach as in the InputSystem editor to
identify which note/channel to bind. I do this by attaching an event
handler to all available MIDI devices onWillNoteOn events, and when that
listener is called, it removes itself from all the events, stores the
device & note/cc, and adds a new listener.

Would there be a different way to implement this functionality? It worked
fine in MidiJack (and was simpler due to the single point for callbacks on
the MidiMaster object), but if there's a better approach I am fine to use
that.

**Comment by keijiro** [comment]
You can use the callback to store input information and remove the callback later in `Update`, `LateUpdate` or something like them.

Yes, it's simpler in the old system. That's the general sentiment about the new system (it's a bit difficult to use but can handle complex things in a reasonable way).

**Comment by Tossrock** [comment]
My actual use case involves ScriptableObjects, not MonoBehaviors, so Update/LateUpdate solution is not great for me without introducing global state / singletons etc. However, if you consider this correct behavior, I can work around it on my own. Thank you for making the library in the first place!
