### ISSUE TITLE
Parsing different channels (virtual MIDI ports)

### ISSUE THREAD

**Issue by michelezaccagnini** [keijiro/Minis#29]
I am using virtual midi ports ( [loopMIDI app](https://www.tobias-erichsen.de/software/loopmidi.html)). I have midi coming out of a DAW from different channels. I a PlayerInput for each object I want to animate via midi. I attached a Midi Device Assigner to each object
![image](https://user-images.githubusercontent.com/11492957/192034103-44e9bc85-3a34-43ad-be65-894d866e7ddd.png)

Then I have a simple script to get the player Input data and change the transform 
```
public class ObjectController : MonoBehaviour
{
    private PlayerInput playerInput;
    private InputAction getCC5;
    private InputAction getCC9;
    public Vector3 displace; 

    private void Awake()
    {
        playerInput = GetComponent<PlayerInput>();
        getCC5 = playerInput.actions["GetCC5"];
        getCC9 = playerInput.actions["GetCC9"];

    }
    void Update()
    {
        float cc5 = getCC5.ReadValue<float>();
        float cc9 = getCC5.ReadValue<float>();
        Vector3 pos = new Vector3(0, cc9, cc5);
        transform.position = pos + displace;
    }
}
```
The different channels assigned in the Midi Device Assigner don't seem to affect the object though.
What am I missing?

**Comment by keijiro** [comment]
First of all, I think you shouldn't use Awake but Start. It's probably irrelevant to this problem, though.

**Comment by michelezaccagnini** [comment]
Ok, I will fix that. Is the problem related to virtual MIDI? is it possible to modify the Midi device assigner to account for that?
Thank you!

**Comment by keijiro** [comment]
>  Is the problem related to virtual MIDI?

I'm not sure at the moment.

I'd recommend trying the fix above first.

**Comment by michelezaccagnini** [comment]
The problem persists using `Start()`
```
void Start()
    {
        playerInput = GetComponent<PlayerInput>();
        getCC5 = playerInput.actions["GetCC5"];
    }
```
I tried the ``DeviceQuery.cs`` script which seems to work fine. So names and channels are recognized correctly. The problem is the interaction between the Midi Device Manager and the Player Input: the latter ignores the former?

**Comment by keijiro** [comment]
How about moving these lines into `Update`?

```
playerInput = GetComponent<PlayerInput>();
getCC5 = playerInput.actions["GetCC5"];
```

**Comment by michelezaccagnini** [comment]
Same behavior, unfortunately.

**Comment by keijiro** [comment]
Is your device detected on Input Debugger?

**Comment by michelezaccagnini** [comment]
yes, all seems to be working there
![image](https://user-images.githubusercontent.com/11492957/192782311-e3440d58-74aa-452e-8235-7ad1ab8a0e7f.png)

**Comment by michelezaccagnini** [comment]
I am trying to get the ``Minis.MidiDevice`` directly in my script so that I can make sure to only get values from the single channels. I am not having any luck so far...
I am using the ```Search()``` function, found in the ``DeviceQuery.cs``, which returns a ``MidiDevice``. Then my plan is to check for ``channel`` value and have an if statement to give me the output if there is a match

```
MidiDevice Search()
        {
            // Matcher object with Minis devices
            var match = new InputDeviceMatcher().WithInterface("Minis");

            // Product name specifier
            if (!string.IsNullOrEmpty(_productName))
                match = match.WithProduct(_productName);

            // Channel number specifier with a capability match
            if (_channel >= 0 && _channel < 16)
                match = match.WithCapability("channel", _channel);

            // Scan all the devices found in the input system.
            foreach (var dev in InputSystem.devices)
                if (match.MatchPercentage(dev.description) > 0)
                    return (MidiDevice)dev;

            return null;
        }
```
Not sure where to run the ``Search()`` loop though

**Comment by michelezaccagnini** [comment]
This works if I don't change midi devices, if I add new channels it won't work though.
I need to implement a ``OnDeviceChange()`` for that. Please let me know if this seems like a good way to go about this, still kinda new to this...
```
[RequireComponent(typeof(PlayerInput))]
    sealed class myDeviceAssigner : MonoBehaviour
    {
        // Search by a product name (regex-able)
        [SerializeField] string _productName = null;

        // Search by a channel number
        [SerializeField] int _channel = -1;
        private PlayerInput playerInput;
        private InputAction getCC21;
        private int found_channel = 20;
        MidiDevice Search()
        {
            // Matcher object with Minis devices
            var match = new InputDeviceMatcher().WithInterface("Minis");

            // Product name specifier
            if (!string.IsNullOrEmpty(_productName))
                match = match.WithProduct(_productName);

            // Channel number specifier with a capability match
            if (_channel >= 0 && _channel < 16)
                match = match.WithCapability("channel", _channel);

            // Scan all the devices found in the input system.
            foreach (var dev in InputSystem.devices)
                if (match.MatchPercentage(dev.description) > 0)
                    return (MidiDevice)dev;

            return null;
        }

        System.Collections.IEnumerator Start()
        {
            while (true)
            {
                var device = Search();

                if (device != null)
                {
                    found_channel = device.channel;
                    break;
                }

                yield return new WaitForSeconds(0.1f);
            }
        }
        private void Update()
        {
            if(found_channel == _channel)
            {
                playerInput = GetComponent<PlayerInput>();
                getCC21 = playerInput.actions["GetCC21"];
                float cc21 = getCC21.ReadValue<float>();
                Debug.Log(cc21);
            }
           
        }
    }
```

**Comment by keijiro** [comment]
I think you should use the onDeviceChange callback.

https://github.com/keijiro/Minis/blob/master/Assets/Script/DeviceCallback.cs#L12

**Comment by michelezaccagnini** [comment]
It does not work because every time I add another channel the ``PlayerInput`` will parse that also. Is there not a way to get the value directly from the ``Minis.MidiDevice``? It seems like the ``InputSystem`` is unable to be assigned a single channel and will parse _any channel that is coming in. 
I really would like this to work. Do you think it can be fixed? I am switching from Shader programming to Unity to work on audiovisuals and this feature is very important for what I am working on. Thanks as always

**Comment by keijiro** [comment]
You may be surprised, but I'm not a specialist of the Input System, so my advice might be wrong.

My impression is that you shouldn't use `PlayerInput`. It's designed for assigning gamepads to player input in game applications, and it's clearly different from your purpose.

For example, I used custom input handlers in VfxMinisExamples.

https://github.com/keijiro/VfxMinisExamples

You can implement your own handler that suits your purpose.

**Comment by michelezaccagnini** [comment]
You are right: using ``PlayerInput`` was the wrong approach. This seems to work fine
```
        private float ccVal;
        [SerializeField] int _channel;
        private void Start()
        {
            InputSystem.onDeviceChange += (device, change) =>
            {
                if (change != InputDeviceChange.Added) return;

                var midiDevice = device as Minis.MidiDevice;

                if (midiDevice == null) return;

                if(midiDevice.channel == _channel)
                {
                    midiDevice.onWillControlChange += (cc, value) => {
                        ccVal = value;
                    };
                }
                
            };
        }

        // Update is called once per frame
        void Update()
        {
            transform.position = new Vector3(ccVal, 0, 0);
            Debug.Log(ccVal);
        }
    }
```

Thanks so much for your help!
