### ISSUE TITLE
Sending data back to my midi controller to control lights

### ISSUE THREAD

**Issue by atesija** [keijiro/Minis#31]
Is it possible to send information back to the midi controller to change lights on it? One use case is when I have an effect active it would be nice to light up the button that controls it.

**Comment by keijiro** [comment]
The Input System only supports input (because it's an input system!), so Minis only supports input too. You have to use the backend (RtMidi) to communicate with the MIDI devices.

https://github.com/keijiro/jp.keijiro.rtmidi

**Comment by atesija** [comment]
Oh perfect! I'll give that a try and let you know if I have questions there. Thanks!
