### ISSUE TITLE
Performance issues on Android

### ISSUE THREAD

**Issue by AdrianBotana** [keijiro/Minis#34]
I'm using your plugin, thanks by the way, to help with the level editor of a rhythm game. However, when I build into Quest, the performance is noticeable cause it goes into build. ¿Can you make a check to select platform? I don't even know if android can handle MIDI.

**Comment by keijiro** [comment]
As noted on README, Minis doesn't support Android.

**Comment by keijiro** [comment]
I close this issue as answered. Please reopen it for further problems.
