### ISSUE TITLE
Not an issue, but a question on android/quest

### ISSUE THREAD

**Issue by wildgoose789** [keijiro/Minis#36]
Hi, firstly thanks for making these, they are really useful! I have integrated minis into a unity project and all works well, however I am building out to a Quest 2 and want it to recognise the midi, preferably from a direct cable connection. Someone told me minis does not support android, is there a workaround for this or the same question if using midijack? Any help would be greatly appreciated!

**Comment by keijiro** [comment]
The simple answer is no, there is no workaround. Please check #3 for further discussion.
