### ISSUE TITLE
[noob] basic implementation unclear from the documentation

### ISSUE THREAD

**Issue by kabouterPop** [keijiro/Minis#9]
Keijiro san, sorry for a question that is likely trivial.  I am trying to setup a template for a keyboard, both from a new 2D project and referencing your "minis-master."  Minis appears to be set up the same in both. I am failing to understand how to assign the midi input to a sprite (key), nor can I find the menu GUI you show in the beginning of your documentation (https://unitylist.com/p/sds/Minis).

For a keyboard of any size, do I assign the scripts under Minis--runtime to each key, to the group that contains all keys, or somewhere else?  My first goal would be to assign a trigger to one octave of piano keys, accepting any octave from the input keyboard source.

I would be grateful for any hep you can give, and would be happy to share my additional documentation and basic keyboard template with you in return.
Thank you.

**Comment by kabouterPop** [comment]
keijiro san,
I have made progress that I hope will shorten any response you may have been considering.  I understand now that your Sphere example has the MidiDeviceAssigner scripts attached to it, and then it gets its input from the Sphere Actions (input actions).  Thus my main question becomes: for a keyboard, would I then assign the MidiDeviceAssigner script  and an input action for the respective note to every key?  Additionally, in my input action, I can bind to a note as you've shown (now I know where that gif comes from), but I cannot find the option you have of "Use in control scheme: MIDI device" checkbox.  I wonder if I'm still missing something important as a result.
Kind regards,
Andrew
yours:
![image](https://user-images.githubusercontent.com/67828440/104368304-2f8ac180-551c-11eb-87b3-5adc09883ae4.png)

mine:
![image](https://user-images.githubusercontent.com/67828440/104368369-43362800-551c-11eb-9f13-980a49c0677f.png)

**Comment by keijiro** [comment]
I think VfxMinisExample would be a better example for your use-case.

https://github.com/keijiro/VfxMinisExamples

Please check the "Animator" scene contained in the repository. Also check the `VfxMidiNoteAnimator.cs` script.

https://github.com/keijiro/VfxMinisExamples/blob/master/Assets/Animator/VfxMidiNoteAnimator.cs

**Comment by kabouterPop** [comment]
Thank you

**Comment by Liam-McHara** [comment]
@kabouterPop From the screenshots you've shared, I see keijiro has the "**All** Control Scheme" option selected (top-left corner) while you have the "**No** Control Scheme". I would try changing that ;)
Good luck!

**Comment by kabouterPop** [comment]
@Liam-McHara, thanks. I'd finally discovered that after a while reading into the new input system.  I've made some decent progress and now have a decent understanding of how Minis works after reading the c# code.  Like many hobbyists, time is split so I haven't quite gotten to the basic implementation of the one-octave keyboard triggering events on any like note...but I think I'm close. If I can get it set up, I plan to share it as a  starter project.
